apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  labels:
    app: pagamentos
spec:
  replicas: {{.Values.pagamentos.replicaCount}}
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      hostname: pagamentos-ms
      containers:
      - name: pagamentos
        #image: leonardosartorello/java-pagamentos-k8s:v3
        image: {{.Values.pagamentos.image}}
        ports:
        - containerPort: {{.Values.pagamentos.image}} 
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD