apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  labels:
    {{- include "cris-estudos.labels" .| nindent 4 }}
    app: pedidos
spec:
  replicas: {{.Values.pedidos.replicaCount}}
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      hostname: pedidos-ms
      containers:
      - name: pedidos
        #image: leonardosartorello/java-pedidos-k8s:v3
        image: {{.Values.pedidos.image}}
        ports:
        - containerPort: {{.Values.pedidos.port}}
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              #key: DB_HOST
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              #key: DB_PASSWORD
              key: mysql-root-password # chave de acesso que foi gerado de forma automatica pelo chart