apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  labels:
    {{- include "cris-estudos.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "server"
  replicas: {{ .Values.server.replicaCount }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        image: {{ .Values.server.image }}
        ports:
        - containerPort: {{ .Values.server.port }}
          name: server
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: SERVER_HOST
