configMap: 
  name: dados
  data:
    SERVER_HOST: "http://server-0.server:8081/eureka,http://server-1.server:8081/eureka"
    DB_HOST: "mysql"

gateway:
  replicaCount: 2
  image: crisdockerz/java-gateway-microsservico:v3
  port: 80

pagamentos:
  replicaCount: 2
  image: crisdockerz/java-pagamentos-microsservico:v3
  port: 40000

pedidos:
  replicaCount: 2
  image: crisdockerz/java-pedidos-microsservico:v3
  port: 40001

